name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-xcframework]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Modify Package.swift
        run: |
          echo "Modifying Package.swift..."
          sed -i 's#url: "https://github.com/radarlabs/radar-sdk-ios/releases/download/.*/RadarSDK.xcframework.zip"#url: "https://github.com/radarlabs/radar-sdk-ios/releases/download/${{ github.event.client_payload.release }}/RadarSDK.xcframework.zip"#g' Package.swift
          sed -i 's#checksum: ".*"#checksum: "${{ github.event.client_payload.checksum }}"#g' Package.swift
      # open a pull request with the new sdk version
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Automated radar-sdk-ios version bump to ${{ github.event.client_payload.release }}
          token: ${{ secrets.GITHUB_TOKEN }}